"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";

export default function Page() {
  const router = useRouter();
  const [url, setUrl] = useState("");

  const analyze = async () => {
    router.push(`/weblens/hypotheses?url=${url}`);
  };

  return (
    <main className="flex-center min-h-screen w-full;">
      <section className="w-4/5 flex-col-center gap-10">
        <h1 className="text-6xl text-center text-transparent bg-clip-text bg-gradient-to-r from-teal-300 to-amber-300">
          A/B test your website using autogenerated insights.
        </h1>
        <label
          htmlFor="url"
          className="flex-row-center gap-2 rounded-full bg-slate-50 text-purple-950 pl-4 pr-2 py-1 w-fit has-[:focus]:outline outline-amber-600"
        >
          <input
            type="text"
            id="url"
            name="url"
            value={url}
            onChange={(e) => setUrl(e.target.value)}
            placeholder="Enter URL here"
            className="outline-none"
            required
          />
          <button
            disabled={!url}
            onClick={analyze}
            className="btn rounded-[inherit] bg-amber-600 font-bold disabled:opacity-50"
          >
            Analyze
          </button>
        </label>
      </section>
    </main>
  );
}
